services:
  - type: web
    name: minkoju-library
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production